"""Perfis de exemplo da iteração do prompt de perfis por ator (24/09/2026).

Escritos seguindo os prompts de challenge/prompts/actor_profile/ na versão 4846c668f7ca (teto de
800 palavras), a pedido do usuário, que não quis gastar GPU na fase de iteração: o teste do prompt
foi feito por mim (Claude) no papel do modelo, lendo as falas completas dos 6 atores contrastantes
(fonte: challenge/artifacts/cache/hearing_actors/actors_multi_hearing.jsonl, com data e assunto
juntados do LDS), sempre com todas as falas numa chamada só. Cada perfil de material rico passou por
uma auditoria adversarial de fundamentação contra as falas originais e as distorções apontadas foram
corrigidas antes desta versão.

Em 24/09/2026 o map_reduce e o orçamento de tokens saíram do runner, junto com os três prompts de
notas; os prompts renderizados dos 301 atores (com e sem --anonymize) ficaram idênticos byte a byte
aos da 4846c668f7ca, e a versão equivalente passou a ser 356d48e7b166.

Estes exemplos NÃO são saída de challenge/utils/generate_actor_profiles.py e não devem ser
misturados aos artefatos gerados pelo script; servem de referência de qualidade-alvo do prompt.
"""

PROMPT_VERSION = "4846c668f7ca"

PROFILES: dict[str, dict[str, str]] = {
    "JOSÉ GUIMARÃES": {
        "profile": (
            "José Guimarães fala em nome do Governo na audiência de 25 de outubro de 2023 sobre "
            "segurança pública: registra o diálogo mantido na véspera com a presidente da "
            "comissão, deputada Bia Kicis, e com o líder Evair, atribui a decisão do ministro "
            "Flávio Dino de comparecer à comissão ao respeito que a presidente sempre demonstrou "
            "ao ministro e deseja uma boa discussão sobre as questões de segurança, avisando que "
            "não poderá permanecer por causa de votações. Na audiência de 9 de agosto de 2023, "
            "sobre insumos para a saúde, sua única fala é o aviso de que o deputado Guilherme o "
            "substituirá."
        ),
    },
    "DEYVID SOUZA BACELAR DA SILVA": {
        "profile": (
            "Falando pela FUP, a Federação Única dos Petroleiros, Deyvid Souza Bacelar da Silva "
            "combateu em junho e julho de 2022 a venda de refinarias da Petrobras, feita, diz, na "
            "bacia das almas: cita a retomada dos teasers da REFAP, da REPAR e da RNEST, "
            "considera muito prejudicial a privatização da SIX, em São Mateus do Sul, e sustenta "
            "que a REGAP, se privatizada, geraria mais um monopólio regional, preços ainda mais "
            "altos e desabastecimento nos rincões de Minas Gerais. Afirma que a RLAM, na sua "
            "Bahia, valia de 3,6 bilhões a 4 bilhões de dólares segundo XP Investimentos, BTG "
            "Pactual e INEEP e foi vendida por 1 bilhão e 850 milhões de dólares, e que a LUBNOR "
            "daria a um empresário de Curitiba, ligado à Prefeitura da cidade, o monopólio do "
            "asfalto no Nordeste. Aponta três riscos: desabastecimento, pois o Brasil, diz, "
            "importa entre 20% e 25% do diesel de refinarias estadunidenses, a refinaria baiana, "
            "do Fundo Mubadala, de Abu Dhabi, prefere exportar óleo combustível bunker a "
            "abastecer o mercado interno, e a ANP teria sinalizado falta de gás de cozinha caso "
            "as refinarias dos teasers sejam privatizadas junto com a SIX e a REPAR; perpetuação "
            "do Preço de Paridade de Importação, pois só o controle acionário da União, afirma, "
            "permite outra política de preços; e dano às economias locais, por precarização do "
            "trabalho e queda da massa salarial e por sonegação fiscal, citando a acusação do "
            "presidente do SINDIPETRO do Amazonas de que a Atem sonega impostos.\n\n"
            "Chama de escuso o acordo entre a Petrobras e o CADE que exigiu a venda de metade da "
            "capacidade de refino a partir do questionamento de uma associação de distribuidoras "
            "do Ceará, estranha que o jurídico da empresa não o tenha judicializado e endossa a "
            "avaliação do senador Jean Paul Prates de que parece ter havido prevaricação. "
            "Qualifica as privatizações de ilegais e inconstitucionais e considera ilegal a "
            "nomeação, pelo Presidente da República, de um presidente da Petrobras sem currículo "
            "nem experiência, anunciando ações judiciais da FUP e da ANAPETRO. Cobra que a gestão "
            "revele o conteúdo do celular corporativo entregue por Roberto Castello Branco, "
            "ex-presidente que preside o Conselho de Administração da 3R Petroleum, compradora de "
            "ativos vendidos em sua gestão, e defende, com o deputado Paulo Ramos, uma CPI das "
            "privatizações. Com base em matéria do repórter Renê Ruschel, aponta o engenheiro "
            "químico Jorge Hardt Filho, pai de Gabriela Hardt, como envolvido em espionagem "
            "industrial na entrega da SIX a um grupo canadense já investigado pela Petrobras.\n\n"
            "Argumenta que, desde a quebra do monopólio do petróleo em 1997, nenhuma refinaria "
            "foi construída pelo capital privado, e atribui a importação de cerca de 15% dos "
            "derivados à falta de retomada de obras paradas desde 2015 pela Operação Lava-Jato, "
            "como o COMPERJ e a segunda metade da RNEST, ambos com mais de 80% de avanço, e as "
            "refinarias Premium I e II. Cita botijão de 13 quilos entre 120 e 145 reais, gasolina "
            "a 8,30 reais o litro na sua terra e diesel a 7,20; altas de 165% no diesel, 159% na "
            "gasolina e 119% no gás de cozinha no governo Bolsonaro contra 21% de reajuste do "
            "salário mínimo; 101 bilhões de reais em dividendos no ano anterior, 47 bilhões deles "
            "a minoritários, e 48 bilhões no primeiro trimestre de 2022. Critica a PEC dos "
            "Combustíveis por destinar orçamento público a esses lucros. Diz aprovada uma greve "
            "nacional e promete a maior da história dos petroleiros se o governo tentar retirar "
            "da União o controle acionário, como fez com a Eletrobras. Quer que morra na Comissão "
            "de Desenvolvimento Econômico o projeto apresentado por Bolsonaro que, segundo ele, "
            "autoriza a venda do óleo-lucro do pré-sal, desvincula royalties carimbados para "
            "saúde e educação e antecipa mais de 400 bilhões de reais em receitas, o que chama de "
            "crime.\n\n"
            "Em maio de 2023 passou a apoiar o poço pioneiro na Margem Equatorial, que segundo "
            "ele não é a foz do Amazonas, registrando que fora contrário ao licenciamento no "
            "governo anterior, quando não via nas cúpulas da Petrobras e do IBAMA preocupação "
            "ambiental. Cita estudos da Petrobras de 2015 e 2022 segundo os quais eventual "
            "vazamento não tocaria a costa, afirma que a empresa nunca teve vazamento em poço "
            "pioneiro e levanta a hipótese de a crise na imprensa ter sido fabricada no governo "
            "anterior. Menciona 388 bilhões de reais em dividendos nos dois últimos anos daquele "
            "governo e quer essa riqueza na transição energética justa, com diálogo com "
            "comunidades indígenas, quilombolas e ribeirinhas e com a atividade servindo ao Norte "
            "e ao Nordeste: os projetos de pesquisa, desenvolvimento e inovação no Norte seriam "
            "só 7% do que a Petrobras poderia ali fazer, com universidades federais da região "
            "preteridas. Defende o setor energético como política de Estado, citando a Noruega da "
            "Statoil, hoje Equinor."
        ),
    },
    "Jorge Solla": {
        "profile": (
            "Entre agosto e dezembro de 2023, Jorge Solla dedica a maior parte das falas à "
            "reconstrução do Sistema Único de Saúde pelo governo do presidente Lula e pela "
            "ministra Nísia Trindade, contraposta à destruição que atribui ao governo anterior. "
            "Acima da perda orçamentária, considera que o pior legado daquele período foi a "
            "demolição da liderança técnica e política do Ministério da Saúde, o farol do SUS; "
            "comemora a reconquista dessa autoridade, a pactuação retomada com CONASS, CONASEMS e "
            "Conselho Nacional de Saúde e os mais de 4 mil serviços refinanciados em cerca de dez "
            "meses.\n\n"
            "Diz-se profissional de saúde pública, epidemiologista e não imunologista, perto de "
            "completar 39 anos de formado no fim de 2023. Conta que foi sanitarista em distrito "
            "sanitário na periferia de Salvador, onde passava, às vezes, um mês reunindo "
            "associações de moradores, mães e igrejas para o Dia D da vacinação de pólio, que "
            "atuou como Secretário de Atenção à Saúde no primeiro governo Lula, quando participou "
            "da criação do SAMU, e que, à frente da Secretaria de Saúde da Bahia a partir de "
            "2007, bloqueou surtos de sarampo no interior do estado com uma campanha estadual de "
            "vacinação.\n\n"
            "Na vacinação, seu tema mais constante, o tom endurece: em agosto fala em retrocesso "
            "de 30 anos na cobertura vacinal, atribuído às fake news e à abordagem do "
            "ex-presidente; em novembro cita municípios que caíram de 90% ou 95% de cobertura, "
            "dez anos atrás, para 35% ou 40%, e passa ao confronto aberto com o que nomeia "
            "movimento antivacina, acusado de crime sanitário e de uso eleitoreiro e "
            "político-partidário da saúde. Rebate alegações como \"a vacina não fica no "
            "braço\", \"a "
            "vacina leva à mutação\", um \"índice de causalidade\" de mortes em 400 autópsias e o "
            "\"nexo causal filmado\", e retruca que filmada foi a corrupção de 1 dólar por dose na "
            "negociata da venda das vacinas. Denuncia como pregação antivacina uma audiência na "
            "Comissão de Fiscalização Financeira e Controle montada sem Ministério da Saúde, OPAS "
            "ou universidades. Propõe o registro digital individualizado de todas as vacinas, "
            "como já ocorre com a da COVID-19, e defende mobilizar Bolsa Família, escola e "
            "agentes comunitários de saúde e de combate às endemias para localizar crianças não "
            "vacinadas.\n\n"
            "No financiamento, sustenta que emenda parlamentar não pode custear serviços "
            "regulares e que o governo passado criou duas classes de hospitais filantrópicos e de "
            "municípios, com o amigo do rei recebendo até o dobro enquanto o Hospital Irmã Dulce, "
            "o maior filantrópico do Norte e do Nordeste, seguia com contrato nos valores de "
            "2016. Agradece à ministra a habilitação, em maio, de oito hospitais e 25 "
            "policlínicas regionais inaugurados depois de 2016 sem verba federal, a recuperação "
            "dos contratos do Irmã Dulce e do Martagão Gesteira, e cobra a inclusão do Hospital "
            "Aristides Maltez. Celebra os 1.800 novos veículos do SAMU e as 50 ambulâncias "
            "entregues na Bahia após 6 anos sem reposição de uma frota antes trocada a cada 5 "
            "anos, e lembra a compra de aceleradores lineares pela presidenta Dilma, 80 se não se "
            "engana, sete deles só para a Bahia. No Mais Médicos, afirma que as cerca de 7 mil "
            "vagas privadas do governo Dilma foram abertas só em municípios sem curso de medicina "
            "e vê indícios, sem comprovação, de que a moratória de 5 anos foi negociada para "
            "escancarar a judicialização, com 15 mil vagas abertas na Justiça em cidades que já "
            "tinham cursos e mais de 30 mil pendentes.\n\n"
            "Pede apoio a projeto aprovado na Comissão de Saúde que cria um fundo para "
            "emergências em saúde pública, para novas pandemias e eventos climáticos como o do "
            "Rio Grande do Sul, defende o Complexo Industrial de Saúde para ampliar a produção "
            "nacional de insumos e classifica como genocídio a situação da população ianomâmi, "
            "destacando a reabertura de sete polos de saúde indígena e a resolução aprovada na "
            "76ª Assembleia da OMS.\n\n"
            "Sobre a concessão da ViaBahia, em 28 de novembro, diz não ser a priori contrário a "
            "concessões, mas avalia que na grande maioria dos casos a promessa de investimento e "
            "qualidade não se cumpre; cita a energia elétrica em São Paulo e afirma que Amazonas, "
            "Rio Grande do Norte e Bahia, onde estão as refinarias privatizadas, pagam mais caro "
            "pelos combustíveis. Responsabiliza também o Estado, que não pode se eximir de "
            "fiscalizar os contratos, e defende as três PPPs de saúde de sua gestão na Bahia, "
            "entre elas o primeiro hospital do SUS por PPP no país, de 2010. Cobra que a COESA, "
            "sucedânea da OAS, inicie as obras da BR-030 ou sofra distrato, atribuindo à "
            "Lava-Jato a destruição das grandes construtoras. Em dezembro, elogia o ministro dos "
            "Direitos Humanos, saúda a reconstrução dos espaços de participação social e destaca "
            "o Viver sem Limite, após 6 anos sem investimento em novos centros de reabilitação."
        ),
    },
    "RODRIGO SARAIVA MARINHO": {
        "profile": (
            "Rodrigo Saraiva Marinho denuncia, em agosto de 2023, ilegalidades e abusos do "
            "Supremo Tribunal Federal e, em dezembro, sustenta que o tribunal já passou do "
            "ativismo judicial e descumpre a lei e a Constituição; responsabiliza Alexandre de "
            "Moraes pela morte do preso Clezão, por não analisar parecer do Ministério Público "
            "Federal recebido em 1º de setembro; essa morte, diz, tem dono. Defende que os presos "
            "do 8 de janeiro, inclusive os que quebraram e cometeram crime, têm direito ao devido "
            "processo legal, e enquadra na Lei de Abuso de Autoridade (artigos 9º, 12, 13 e 20) "
            "audiências de custódia que levaram quase 48 horas e, em vários casos, até 5 dias, "
            "pessoas colocadas em ônibus sem saber que estavam presas, vacina exigida até para "
            "audiência virtual e advogados impedidos de falar com clientes. Imagina o juiz Sergio "
            "Moro como autor dessas decisões para expor dois pesos e duas medidas: o vídeo de "
            "Flávio Dino questionando urnas eletrônicas não gera prisão, críticas de outros às "
            "mesmas urnas geram. Argumenta que não existe golpe sem armas e aponta como "
            "beneficiados do 8 de janeiro o Executivo de Lula, que tirou as pessoas da rua, e "
            "Moraes, que fundamentou a ideia de golpe. Cobra do vice-presidente da OAB, Rafael, "
            "atitude pública contra o STF pela violação das prerrogativas dos advogados e pelas "
            "mais de 1.400 pessoas sem prerrogativa de foro.\n\n"
            "Apresentando-se como diretor-executivo do Instituto Livre Mercado e secretário da "
            "Frente Parlamentar pelo Livre Mercado, lista decisões que considera contrárias à "
            "norma: o HC 124306, sobre a interrupção da gestação até o terceiro mês, tema que "
            "caberia ao Congresso; a ADPF 635, que proibiu operações em favelas do Rio na "
            "pandemia, pois suprema corte não faz política pública; a suspensão da nomeação de "
            "Ramagem para a chefia da PF, um cargo em comissão; a mudança da Lei das Estatais em "
            "liminar para nomear um amigo de Lula à presidência do BNDES; e o fatiamento do "
            "impeachment, anunciado pelo então presidente e julgado por Rosa Weber em sessão "
            "virtual. Ataca o inquérito das fake news, aberto de ofício por Toffoli após capa da "
            "revista Crusoé e entregue a Moraes por portaria, sem sorteio, no qual Daniel "
            "Silveira ficou 9 meses preso em regime fechado. Cita balanço da equipe de Ricardo "
            "Lewandowski, 117.784 decisões em 17 anos, 84% monocráticas, e devolve a Luís Roberto "
            "Barroso, presidente do CNJ, a responsabilidade pelas quatro mortes diárias nos "
            "presídios. Chama de censura prévia a proibição, por Cármen Lúcia, de documentário da "
            "Brasil Paralelo sobre a facada contra Bolsonaro, e condena o bloqueio das contas da "
            "filha de um acusado e do empresário Afrânio, do Coco Bambu, punido por um joinha em "
            "grupo de WhatsApp. Para ele, a democracia por si só é ditadura da maioria; a "
            "democracia liberal protege a menor minoria, e os Poderes devem se enfrentar, sem a "
            "harmonia inserida por Michel Temer na Constituinte.\n\n"
            "Em abril e maio de 2024 volta-se à agenda econômica. Contra o PLP 12/2024, argumenta "
            "que falta subordinação para caracterizar vínculo, que os motoristas rejeitaram a CLT "
            "e que o projeto veda acordo individual ao prever só convenção coletiva obrigatória; "
            "sugere como emenda desobrigar o cumprimento da convenção e propõe modalidade "
            "inspirada no MEI Caminhoneiro, rejeitada porque, afirma, o MEI tira o sindicato da "
            "jogada. Sustenta que o preço mínimo quebra pequenas cidades e o interior, que o "
            "projeto prejudica pequenos players como Vou Passar e Vem me Pegar e fecharia o "
            "InDrive, e que os maiores beneficiados dos aplicativos são as classes C, D e E. "
            "Nesse debate, em resposta ao secretário Adroaldo sobre previdência, atribui à Folha "
            "de S.Paulo o déficit atuarial de 6 trilhões de reais da Previdência, e vê tutela "
            "violenta do trabalhador quando o governo define o que é melhor para ele. Cita a "
            "frase de Natalício Bezerra, do Sindicato dos Taxistas Autônomos de São Paulo, de que "
            "o pobre não vai querer ter o que o rico tem, e lembra ter sido advogado na ADPF 449, "
            "que derrubou a lei do prefeito Roberto Cláudio, do PDT, contra os aplicativos em "
            "Fortaleza, sua cidade. Em defesa do saque-aniversário do FGTS, atribui à Caixa "
            "Econômica Federal o crescimento do fundo de 418 bilhões de reais em 2019 para 570 "
            "bilhões, cita pesquisa em que 57% dos trabalhadores pagam dívidas atrasadas e que, "
            "para 70% de quem saca, o valor é de 500 reais; compara os juros de 1,78% da "
            "antecipação do FGTS aos até 20% ao mês de negativados e pede acesso ao cálculo "
            "atuarial invocado pelo secretário Carlos Augusto; pergunta-se se o Ministério do "
            "Trabalho acha que tutela os trabalhadores e ironiza a genialidade de definir, num "
            "passe de mágica, a taxa de juros ideal. Aponta o Ceará, seu estado, em calamidade de "
            "segurança pública, para ele o principal problema do Brasil."
        ),
    },
    "Bia Kicis": {
        "profile": (
            "Bia Kicis fez da oposição à vacinação obrigatória de crianças de 6 meses a 5 anos "
            "contra a Covid-19 sua pauta mais insistente: em novembro de 2023 realizou três "
            "audiências sobre o tema na Comissão de Fiscalização Financeira e Controle, que "
            "presidia, com requerimentos próprios. Declara-se vacinada, \"não contra a "
            "COVID\", com "
            "filhos e até a cachorra vacinados, e apoia as vacinas de longa data do PNI, mas "
            "combate a obrigatoriedade desse imunizante, que chama de terapia gênica, denominação "
            "que atribui ao FDA e a médicos. Assina com o Deputado Delegado Paulo Bilynskyj "
            "projeto de lei vedando a inclusão de vacinas não imunizantes no PNI e defende "
            "projetos que impeçam a entrada da vacina da Covid no programa. Cobra do Ministério "
            "da Saúde dados de segurança e eficácia que considera nunca apresentados e pergunta "
            "quantas das 48 crianças mortas, número de estudo que atribui ao próprio Ministério, "
            "tinham comorbidade. Afirma existir uma elite globalista que quer forçar essa "
            "vacinação, inclusive em bebês, com o Brasil como pioneiro, e rejeita cortar o Bolsa "
            "Família ou acionar o Conselho Tutelar contra pais que não vacinarem. Atribui ao Dr. "
            "Chris Flowers a informação de que Dinamarca, Reino Unido, Suíça e Alemanha "
            "restringem obrigação ou recomendação por faixa etária e de que a Islândia proibiu a "
            "vacina para qualquer idade. Pergunta se o termo de consentimento do Guia nº 42, de "
            "2020, da ANVISA é observado e acusa o Dr. Eder Gatti, diretor do PNI, de omitir, no "
            "laudo sobre a morte de Isabelle, 8 dias após dose da Pfizer, estudos sobre "
            "trombocitopenia publicados desde 2021, o que para ela põe em xeque a credibilidade "
            "dele. Cita o caso Bruno Graf, sequelado da vacina da AstraZeneca produzida pela "
            "FIOCRUZ, com nexo causal que diz comprovado, e cobra providências para os "
            "sequelados. Repudia o rótulo de negacionista, repete que a ciência é mutável e feita "
            "de questionamento, declara-se pró-ciência, pró-verdade, pró-vida e pró-família, "
            "contrária ao aborto, e afirma que as crianças pertencem à família, não ao Estado. "
            "Acusou a Ministra Nísia Trindade de descumprir o combinado de 4 horas de audiência, "
            "de tratar parlamentares como criminosos e de mentir, e admitiu pautar sua "
            "convocação.\n\n"
            "Desde agosto de 2023 defende os presos dos atos de 8 de janeiro: sustenta que "
            "vandalismo está longe de ser terrorismo e deve ser respondido como vandalismo, sem o "
            "regime imposto, que a seu ver rasga o devido processo legal, e lembra que a Lei "
            "Antiterror excluiu a motivação política da tipificação, atribuindo ao PT o veto à "
            "inclusão dos movimentos sociais. Relata ter esperado 6 horas na Polícia Federal sem "
            "acesso aos presos e mais de 1 mês pela autorização do Ministro Alexandre para "
            "visitar a Papuda, nunca obtendo a da Colmeia; segundo juízes que diz ter ouvido, as "
            "audiências de custódia foram pró-forma. Propõe transformar o STF em corte "
            "constitucional, retirar sua competência penal originária e acabar com o foro "
            "privilegiado, e afirma ter apresentado, como membro da CCJ na legislatura anterior, "
            "projetos para criminalizar o ativismo judicial. Assinou representação à ONU e "
            "relatou, em abril de 2024, ter estado recentemente com comitiva no Parlamento "
            "Europeu. Nessa data elogiou Glenn Greenwald, Michael Shellenberger, David Ágape e "
            "Eli Viera, avaliou que o X seria a única plataforma ainda com liberdade de expressão "
            "e afirmou que ordens do Ministro Alexandre de Moraes, que se recusa a chamar de "
            "judiciais por não atenderem ao devido processo, mandaram plataformas banir perfis "
            "conservadores, sobretudo com as hashtags #votoimpresso e #eleiçõessistemaauditavel, "
            "ocultando a origem dos banimentos; propôs uma Comissão Geral na Casa. Diz figurar no "
            "inquérito do fim do mundo, aberto sem participação do MP e com pedido de "
            "arquivamento da ex-Procuradora-Geral Raquel Dodge; relata que seus advogados não "
            "conseguiam acesso aos autos e que, depois de a OAB acionar o STF, passaram a acessar "
            "apenas algumas partes do processo. Não se sente representada pela OAB, que a seu ver "
            "descumpre seu papel. Critica Flávio Dino por recusar ordem da CPMI de exibir "
            "imagens.\n\n"
            "Em agosto de 2023 questionou a compra de insulina de laboratório sem registro na "
            "ANVISA, a preterição da vacina japonesa da dengue, testada há mais de 10 anos no "
            "Japão, e a revogação, noticiada pela mídia, do QualiSUS Cardio, programa a que "
            "atribui economia de 280 milhões com OPME. Sobre o apagão, tema de audiência do mesmo "
            "mês, rejeitou a ligação com a desestatização da ELETROBRAS, lembrando apagões em "
            "2009 e 2014 e a participação do Governo Federal, com mais de 34% das ações. "
            "Denunciou sete militares da PMDF presos e sem salário sem decisão condenatória como "
            "violência aos direitos humanos e invoca a imunidade parlamentar do art. 53. "
            "Apresenta-se como advogada, procuradora do Distrito Federal por 24 anos, primeira "
            "mulher eleita para presidir a CCJ e a CFFC e deputada mais votada do DF, com 214.733 "
            "votos."
        ),
    },
    "Erika Kokay": {
        "profile": (
            "Deputada eleita por Brasília, ex-parlamentar distrital por dois mandatos e por muito "
            "tempo presidente da Comissão de Direitos Humanos da Câmara Legislativa, Erika Kokay "
            "sustenta que o hospital psiquiátrico não cabe mais no Brasil. Em julho de 2022 "
            "denunciou um apagão de dados em saúde mental e o financiamento público de leitos "
            "psiquiátricos, de eletrochoques e de comunidades terapêuticas sem padronização de "
            "serviços, avaliação ou controle social; esses recursos, defende, deveriam ir aos "
            "CAPS e à Rede de Atenção Psicossocial, no cuidado em liberdade. A crítica à "
            "desumanização alcança o sistema prisional, que afirma acompanhar há 20 anos no "
            "Distrito Federal: relata fome e perda de peso nos presídios locais, celas para 8 "
            "pessoas com 30 a 40 ocupantes, visitas reduzidas a cada 15 dias e, no caso dos "
            "filhos, a cinco por ano, e grades postas nas salas de aula sem pedido dos "
            "educadores, estimando em por volta de 40% a população carcerária sem sentença. Quer "
            "remição por leitura com metodologia clara, profissionalização ligada ao mercado, "
            "acompanhamento de egressos, revisão da Lei de Drogas e a regulamentação da profissão "
            "de policial penal.\n\n"
            "Na pauta da pessoa com deficiência, propôs em 2023 subcomissões sobre o espectro "
            "autista e sobre violências contra mulheres com deficiência, dupla docência para "
            "estudantes com deficiência e cotas para a arte inclusiva nos editais de fomento. "
            "Defende que a avaliação biopsicossocial da LBI dialogue com a CIF e alcance pessoas "
            "com dor crônica, como quem vive com fibromialgia e lúpus, cuja fala, diz, é ignorada "
            "em perícias aprisionadas à CID; para as doenças raras, por volta de 8 mil segundo "
            "ela, apoia fundo de pesquisa e assistência, licenciamento compulsório diante da lei "
            "de patentes e jornada diferenciada para cuidadores. Desde novembro de 2021 pede "
            "diagnóstico precoce e atendimento multidisciplinar, atacando o nível de "
            "medicalização para TDAH em um Brasil que aponta como um dos países que mais consomem "
            "esses medicamentos no mundo; tendeu a concordar com o Deputado Eduardo Barbosa que "
            "talvez a solução não seja enquadrar o TDAH como deficiência.\n\n"
            "Sobre infância, vê choque insanável entre família acolhedora e adoção pela mesma "
            "família, quer impedir o acolhimento institucional de crianças de até 3 anos e se diz "
            "impactada por algo entre 4% e 5% das crianças acolhidas estarem em famílias "
            "acolhedoras, com 56.812 vagas institucionais contra 1.795 familiares; apoia a PEC "
            "383/17, de piso para o SUAS. Defende a universalização das creches, que diz ter "
            "defendido na incorporação ao FUNDEB em 2007, e anunciou em 2023 a elaboração de uma "
            "política nacional de enfrentamento ao racismo na primeira infância, com letramento "
            "racial.\n\n"
            "Em 2022 responsabilizou o então governo federal pelo crescimento do garimpo ilegal "
            "em territórios indígenas, lembrando o anúncio do então candidato de não homologar "
            "nenhum centímetro, e descreveu um Estado capturado, com a Fundação Palmares na mão "
            "do racismo e a FUNAI com política anti-indigenista; sugeriu uma CPI sobre a "
            "violência contra mulheres e crianças indígenas. Em abril de 2024 elogiou o Ministro "
            "Luiz Marinho pela retirada da urgência do projeto dos aplicativos. Em setembro de "
            "2023 comemorou o arquivamento, no Conselho de Ética, dos processos contra ela e a "
            "Deputada Talíria, abertos para cassar mandatos de seis mulheres que chamaram de "
            "assassinos os aprovadores do marco temporal, contra o qual segue lutando, assim como "
            "contra o PL 490. Cobra a implementação das proposições da CPI do genocídio de jovens "
            "negros, inclusive por decretos e portarias, e afirma que não há bala perdida no "
            "Brasil.\n\n"
            "Classificou de homofóbico o parecer ao PL 580/07 e pediu seu arquivamento com base "
            "na laicidade do Estado, na decisão unânime do STF e nos mais de 80 mil casais "
            "regulamentados; relata ter impedido, com o Deputado Jean Wyllys, o avanço do "
            "Estatuto da Família na Câmara. No feminicídio, cita o Brasil como quinto país do "
            "mundo e, no Distrito Federal, uma mulher morta a cada 10 dias, propondo lei de "
            "valorização e padronização da perícia com formação em gênero.\n\n"
            "Egressa da Caixa, onde participou da luta pelas 6 horas e pela sindicalização, "
            "requereu com o Deputado Tadeu Veneri, em abril de 2024, audiência contra a "
            "transferência das loterias para uma subsidiária privatizável sem aval do Parlamento, "
            "pedindo suspensão da pauta no Conselho de Administração e requerimento de "
            "informação. Considera que o país deveria ter a coragem de revogar a reforma da "
            "Previdência, chama de confisco a cobrança de aposentados e rejeita o conceito de "
            "déficit previdenciário. Apresentou o projeto do MEP, o microempreendedor "
            "profissional, contribuição diferente do MEI que abrange faixa maior de renda, e "
            "outro que reconhece como acidente de trabalho o acidente em exercício laboral, "
            "recorte que cobra também no DPVAT, cuja indenização afirma congelada desde 2006. Em "
            "junho de 2023 defendeu a tarifa zero, negando que exista transporte público no país, "
            "e propôs uma subcomissão do tema na Comissão de Direitos Humanos."
        ),
    },
}


def main() -> None:
    for actor, entry in PROFILES.items():
        words = len(entry["profile"].split())
        print(f"=== {actor} ({words} palavras) ===")
        print(entry["profile"])
        print()


if __name__ == "__main__":
    main()
