from importlib.metadata import version

from bookworm.config import (
    SentenceTransformerSettings,
    SplitConfig,
    TfidfSettings,
    UdvConfig,
    load_split_config,
    load_udv_config,
)
from bookworm.data.dates import (
    ArticleDateCheck,
    DateExtractionSummary,
    MentionCheck,
    WeekdayMention,
    article_date,
    check_article_date,
    summarize_date_extraction,
)
from bookworm.data.io import (
    iter_jsonl,
    load_gated_jsonl,
    load_hearings,
    load_jsonl,
    sha256_of_file,
    verify_sha256,
    write_json,
    write_jsonl,
)
from bookworm.data.schemas import HearingMetadata, HearingRecord, Participant
from bookworm.data.splits import (
    SPLIT_NAMES,
    CutCandidate,
    SplitArtifacts,
    SplitBoundaries,
    SplitName,
    TemporalSplit,
    build_manifest,
    build_report,
    build_temporal_split,
    compute_temporal_split,
)
from bookworm.data.verify_splits import SplitVerification, verify_split_run
from bookworm.errors import (
    BookwormError,
    ConfigError,
    DatasetIntegrityError,
    EmbeddingCacheMissError,
    SplitError,
)
from bookworm.features.encoders import (
    CachedEncoder,
    RunCacheEncoder,
    SentenceEncoder,
    cache_file_name,
    cache_key,
    sentence_encoder_identity,
)
from bookworm.features.tfidf import TfidfEncoder
from bookworm.transcript.offsets import Span, locate_sentence_span, locate_turn_sentence_span
from bookworm.transcript.sentences import (
    TurnSentence,
    enclosing_sentence,
    sentences_agree,
    split_sentences,
    split_turn_sentences,
)
from bookworm.transcript.speakers import resolve_person_speech
from bookworm.transcript.turns import Turn, split_into_turns
from bookworm.udv.build import (
    EvidenceSettings,
    PersonSpeech,
    UdvRun,
    build_hearing_udvs,
    build_udvs,
    resolve_hearing_people,
    select_hearings,
)
from bookworm.udv.coverage import pipeline_description, summarize_run
from bookworm.udv.export import export_hearing
from bookworm.udv.quotes import (
    QuoteMatch,
    QuotePolicy,
    TurnQuoteMatch,
    extract_quotes,
    find_opinion_quote_match,
    find_opinion_turn_quote_match,
    find_quote_match,
    is_trusted_quote,
)
from bookworm.udv.schemas import (
    SUPPORT_TYPES,
    TIERS,
    Actor,
    Evidence,
    Method,
    Provenance,
    SupportType,
    Tier,
    UdvRecord,
    load_udv_jsonl,
    read_udv_jsonl,
    write_udv_jsonl,
)
from bookworm.udv.site import SiteExport, display_title, export_site, site_index_entry
from bookworm.udv.verify import UdvVerification, compare_with_baseline, verify_udv_run

__version__ = version("bookworm")

__all__ = [
    "SPLIT_NAMES",
    "SUPPORT_TYPES",
    "TIERS",
    "Actor",
    "ArticleDateCheck",
    "BookwormError",
    "CachedEncoder",
    "ConfigError",
    "CutCandidate",
    "DatasetIntegrityError",
    "DateExtractionSummary",
    "EmbeddingCacheMissError",
    "Evidence",
    "EvidenceSettings",
    "HearingMetadata",
    "HearingRecord",
    "MentionCheck",
    "Method",
    "Participant",
    "PersonSpeech",
    "Provenance",
    "QuoteMatch",
    "QuotePolicy",
    "RunCacheEncoder",
    "SentenceEncoder",
    "SentenceTransformerSettings",
    "SiteExport",
    "Span",
    "SplitArtifacts",
    "SplitBoundaries",
    "SplitConfig",
    "SplitError",
    "SplitName",
    "SplitVerification",
    "SupportType",
    "TemporalSplit",
    "TfidfEncoder",
    "TfidfSettings",
    "Tier",
    "Turn",
    "TurnQuoteMatch",
    "TurnSentence",
    "UdvConfig",
    "UdvRecord",
    "UdvRun",
    "UdvVerification",
    "WeekdayMention",
    "__version__",
    "article_date",
    "build_hearing_udvs",
    "build_manifest",
    "build_report",
    "build_temporal_split",
    "build_udvs",
    "cache_file_name",
    "cache_key",
    "check_article_date",
    "compare_with_baseline",
    "compute_temporal_split",
    "display_title",
    "enclosing_sentence",
    "export_hearing",
    "export_site",
    "extract_quotes",
    "find_opinion_quote_match",
    "find_opinion_turn_quote_match",
    "find_quote_match",
    "is_trusted_quote",
    "iter_jsonl",
    "load_gated_jsonl",
    "load_hearings",
    "load_jsonl",
    "load_split_config",
    "load_udv_config",
    "load_udv_jsonl",
    "locate_sentence_span",
    "locate_turn_sentence_span",
    "pipeline_description",
    "read_udv_jsonl",
    "resolve_hearing_people",
    "resolve_person_speech",
    "select_hearings",
    "sentence_encoder_identity",
    "sentences_agree",
    "sha256_of_file",
    "site_index_entry",
    "split_into_turns",
    "split_sentences",
    "split_turn_sentences",
    "summarize_date_extraction",
    "summarize_run",
    "verify_sha256",
    "verify_split_run",
    "verify_udv_run",
    "write_json",
    "write_jsonl",
    "write_udv_jsonl",
]
